#!/bin/sh
set -e

#echo "port = ${MYSQL_ADAPTER_PORT}" >> /etc/my.cnf
#echo "binlog_do_db = ${MYSQL_ADAPTER_DATABASE}" >> /etc/my.cnf

mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE ${MYSQL_ADAPTER_DATABASE}; \
CREATE USER '${MYSQL_ADAPTER_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ADAPTER_PASSWORD}'; \
GRANT SELECT, UPDATE, DELETE, INSERT, ALTER, CREATE, DROP ON ${MYSQL_ADAPTER_DATABASE}.* TO '${MYSQL_ADAPTER_USER}'@'%'; \
CREATE USER '${MYSQL_REPLICATION_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${MYSQL_REPLICATION_PASSWORD}'; \
GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE, SUPER ON *.* TO '${MYSQL_REPLICATION_USER}'@'%'; \
FLUSH PRIVILEGES;"
